FIND_PATH(VORBIS_INCLUDE_DIR NAMES vorbis/vorbisfile.h)
MARK_AS_ADVANCED(VORBIS_INCLUDE_DIR)
 
FIND_LIBRARY(VORBIS_LIBRARY NAMES
  vorbis
  libvorbis)
MARK_AS_ADVANCED(VORBIS_LIBRARY)

FIND_LIBRARY(VORBISFILE_LIBRARY NAMES
  vorbisfile
  libvorbisfile)
MARK_AS_ADVANCED(VORBISFILE_LIBRARY)

set (VORBIS_LIBRARIES ${VORBIS_LIBRARY} ${VORBISFILE_LIBRARY})
 
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Vorbis DEFAULT_MSG VORBIS_LIBRARIES VORBIS_INCLUDE_DIR)
